# Generated by Django 4.2 on 2023-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(max_length=200)),
                ('book_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='bookcovers/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
